'use client';

import { useState, useRef } from 'react';
import {
  FileText,
  Download,
  Printer,
  Calendar,
  BarChart3,
  Users,
  AlertTriangle,
  Languages,
  Activity,
  TrendingUp,
  Building2,
  MapPin,
  Share2,
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { useHealthPlatform } from '../health-platform-provider';
import type { SupportedLanguage } from '@/lib/health-platform';

// Localized strings
const REPORT_TEXT: Record<SupportedLanguage, {
  title: string;
  subtitle: string;
  generateReport: string;
  downloadPDF: string;
  print: string;
  share: string;
  reportPeriod: string;
  weekly: string;
  monthly: string;
  quarterly: string;
  summary: string;
  keyMetrics: string;
  totalConversations: string;
  uniqueUsers: string;
  emergenciesHandled: string;
  avgSatisfaction: string;
  categoryBreakdown: string;
  languageUsage: string;
  riskAssessments: string;
  trends: string;
  recommendations: string;
  generatedOn: string;
  generatedBy: string;
  confidential: string;
  pageOf: string;
  noData: string;
}> = {
  en: {
    title: 'Health Report Generator',
    subtitle: 'Generate detailed health analytics reports',
    generateReport: 'Generate Report',
    downloadPDF: 'Download PDF',
    print: 'Print',
    share: 'Share',
    reportPeriod: 'Report Period',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    summary: 'Executive Summary',
    keyMetrics: 'Key Metrics',
    totalConversations: 'Total Conversations',
    uniqueUsers: 'Unique Users',
    emergenciesHandled: 'Emergencies Handled',
    avgSatisfaction: 'Avg. Satisfaction',
    categoryBreakdown: 'Category Breakdown',
    languageUsage: 'Language Usage',
    riskAssessments: 'Risk Assessments',
    trends: 'Trends & Insights',
    recommendations: 'Recommendations',
    generatedOn: 'Generated on',
    generatedBy: 'Generated by Health Platform',
    confidential: 'CONFIDENTIAL - For Official Use Only',
    pageOf: 'Page {current} of {total}',
    noData: 'No data available for this period',
  },
  hi: {
    title: 'स्वास्थ्य रिपोर्ट जनरेटर',
    subtitle: 'विस्तृत स्वास्थ्य विश्लेषण रिपोर्ट बनाएं',
    generateReport: 'रिपोर्ट बनाएं',
    downloadPDF: 'PDF डाउनलोड',
    print: 'प्रिंट',
    share: 'शेयर',
    reportPeriod: 'रिपोर्ट अवधि',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    quarterly: 'त्रैमासिक',
    summary: 'कार्यकारी सारांश',
    keyMetrics: 'मुख्य मैट्रिक्स',
    totalConversations: 'कुल वार्तालाप',
    uniqueUsers: 'अद्वितीय उपयोगकर्ता',
    emergenciesHandled: 'आपातकाल संभाले',
    avgSatisfaction: 'औसत संतुष्टि',
    categoryBreakdown: 'श्रेणी विवरण',
    languageUsage: 'भाषा उपयोग',
    riskAssessments: 'जोखिम आकलन',
    trends: 'रुझान और अंतर्दृष्टि',
    recommendations: 'सिफारिशें',
    generatedOn: 'जनरेट किया गया',
    generatedBy: 'स्वास्थ्य प्लेटफॉर्म द्वारा जनरेट',
    confidential: 'गोपनीय - केवल आधिकारिक उपयोग के लिए',
    pageOf: 'पृष्ठ {current} का {total}',
    noData: 'इस अवधि के लिए कोई डेटा उपलब्ध नहीं',
  },
  mr: {
    title: 'आरोग्य अहवाल जनरेटर',
    subtitle: 'तपशीलवार आरोग्य विश्लेषण अहवाल तयार करा',
    generateReport: 'अहवाल तयार करा',
    downloadPDF: 'PDF डाउनलोड',
    print: 'प्रिंट',
    share: 'शेअर',
    reportPeriod: 'अहवाल कालावधी',
    weekly: 'साप्ताहिक',
    monthly: 'मासिक',
    quarterly: 'त्रैमासिक',
    summary: 'कार्यकारी सारांश',
    keyMetrics: 'मुख्य मेट्रिक्स',
    totalConversations: 'एकूण संभाषणे',
    uniqueUsers: 'अद्वितीय वापरकर्ते',
    emergenciesHandled: 'आणीबाणी हाताळल्या',
    avgSatisfaction: 'सरासरी समाधान',
    categoryBreakdown: 'श्रेणी तपशील',
    languageUsage: 'भाषा वापर',
    riskAssessments: 'जोखीम मूल्यांकन',
    trends: 'ट्रेंड आणि अंतर्दृष्टी',
    recommendations: 'शिफारसी',
    generatedOn: 'तयार केले',
    generatedBy: 'आरोग्य प्लॅटफॉर्मद्वारे तयार',
    confidential: 'गोपनीय - केवळ अधिकृत वापरासाठी',
    pageOf: 'पान {current} चे {total}',
    noData: 'या कालावधीसाठी डेटा उपलब्ध नाही',
  },
  pa: {
    title: 'ਸਿਹਤ ਰਿਪੋਰਟ ਜਨਰੇਟਰ',
    subtitle: 'ਵਿਸਤ੍ਰਿਤ ਸਿਹਤ ਵਿਸ਼ਲੇਸ਼ਣ ਰਿਪੋਰਟਾਂ ਬਣਾਓ',
    generateReport: 'ਰਿਪੋਰਟ ਬਣਾਓ',
    downloadPDF: 'PDF ਡਾਊਨਲੋਡ',
    print: 'ਪ੍ਰਿੰਟ',
    share: 'ਸ਼ੇਅਰ',
    reportPeriod: 'ਰਿਪੋਰਟ ਮਿਆਦ',
    weekly: 'ਹਫ਼ਤਾਵਾਰੀ',
    monthly: 'ਮਹੀਨਾਵਾਰ',
    quarterly: 'ਤਿਮਾਹੀ',
    summary: 'ਕਾਰਜਕਾਰੀ ਸਾਰ',
    keyMetrics: 'ਮੁੱਖ ਮੈਟ੍ਰਿਕਸ',
    totalConversations: 'ਕੁੱਲ ਗੱਲਬਾਤ',
    uniqueUsers: 'ਵਿਲੱਖਣ ਉਪਭੋਗਤਾ',
    emergenciesHandled: 'ਐਮਰਜੈਂਸੀ ਸੰਭਾਲੀਆਂ',
    avgSatisfaction: 'ਔਸਤ ਸੰਤੁਸ਼ਟੀ',
    categoryBreakdown: 'ਸ਼੍ਰੇਣੀ ਵੇਰਵਾ',
    languageUsage: 'ਭਾਸ਼ਾ ਵਰਤੋਂ',
    riskAssessments: 'ਜੋਖਮ ਮੁਲਾਂਕਣ',
    trends: 'ਰੁਝਾਨ ਅਤੇ ਸੂਝ',
    recommendations: 'ਸਿਫ਼ਾਰਸ਼ਾਂ',
    generatedOn: 'ਤਿਆਰ ਕੀਤਾ',
    generatedBy: 'ਸਿਹਤ ਪਲੇਟਫਾਰਮ ਦੁਆਰਾ ਤਿਆਰ',
    confidential: 'ਗੁਪਤ - ਸਿਰਫ਼ ਅਧਿਕਾਰਤ ਵਰਤੋਂ ਲਈ',
    pageOf: 'ਪੰਨਾ {current} ਦਾ {total}',
    noData: 'ਇਸ ਮਿਆਦ ਲਈ ਕੋਈ ਡਾਟਾ ਉਪਲਬਧ ਨਹੀਂ',
  },
};

type ReportPeriod = 'weekly' | 'monthly' | 'quarterly';

// Sample report data
const SAMPLE_REPORT_DATA = {
  summary: {
    totalConversations: 3842,
    uniqueUsers: 1256,
    emergenciesHandled: 47,
    avgSatisfaction: 4.2,
    conversationChange: 15.3,
    userChange: 8.7,
    emergencyChange: -12.4,
    satisfactionChange: 0.3,
  },
  categories: [
    { name: 'Pregnancy Care', count: 892, percentage: 23.2 },
    { name: 'Vaccines & Immunization', count: 756, percentage: 19.7 },
    { name: 'Dengue', count: 612, percentage: 15.9 },
    { name: 'Malaria', count: 524, percentage: 13.6 },
    { name: 'Child Nutrition', count: 489, percentage: 12.7 },
    { name: 'General Health', count: 569, percentage: 14.8 },
  ],
  languages: [
    { name: 'Hindi', code: 'hi', count: 1614, percentage: 42 },
    { name: 'English', code: 'en', count: 1191, percentage: 31 },
    { name: 'Marathi', code: 'mr', count: 653, percentage: 17 },
    { name: 'Punjabi', code: 'pa', count: 384, percentage: 10 },
  ],
  risks: [
    { level: 'Low', count: 2534, percentage: 66 },
    { level: 'Medium', count: 883, percentage: 23 },
    { level: 'High', count: 345, percentage: 9 },
    { level: 'Emergency', count: 80, percentage: 2 },
  ],
  trends: [
    'Dengue-related queries increased by 45% compared to last month',
    'Pregnancy care consultations peaked during morning hours (9-11 AM)',
    'Hindi language usage continues to dominate with 42% of all conversations',
    'Emergency response time improved to average 2.1 seconds',
    'User satisfaction rate maintained above 4.0 for the 3rd consecutive month',
  ],
  recommendations: [
    'Increase dengue prevention awareness content as monsoon season approaches',
    'Consider adding more ASHA workers to handle peak morning traffic',
    'Expand Marathi content library based on increasing regional demand',
    'Implement proactive health reminders for vaccination schedules',
    'Launch community health education campaigns in high-risk areas',
  ],
};

interface ReportGeneratorProps {
  onGenerate?: (period: ReportPeriod) => Promise<typeof SAMPLE_REPORT_DATA>;
}

// Report Preview Component (printable)
function ReportPreview({ 
  data, 
  period, 
  language,
  text,
}: { 
  data: typeof SAMPLE_REPORT_DATA;
  period: ReportPeriod;
  language: SupportedLanguage;
  text: typeof REPORT_TEXT['en'];
}) {
  const periodLabels: Record<ReportPeriod, string> = {
    weekly: text.weekly,
    monthly: text.monthly,
    quarterly: text.quarterly,
  };

  const getDateRange = () => {
    const now = new Date();
    let start = new Date();
    
    switch (period) {
      case 'weekly':
        start.setDate(now.getDate() - 7);
        break;
      case 'monthly':
        start.setMonth(now.getMonth() - 1);
        break;
      case 'quarterly':
        start.setMonth(now.getMonth() - 3);
        break;
    }
    
    const format = (d: Date) => d.toLocaleDateString(
      language === 'en' ? 'en-IN' : `${language}-IN`,
      { day: 'numeric', month: 'short', year: 'numeric' }
    );
    
    return `${format(start)} - ${format(now)}`;
  };

  return (
    <div className="bg-white dark:bg-zinc-900 p-8 space-y-8 print:p-0 print:space-y-6" id="health-report">
      {/* Report Header */}
      <div className="border-b-2 border-primary pb-4 print:border-b">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-12 w-12 rounded-lg bg-gradient-to-br from-blue-600 to-indigo-700 flex items-center justify-center print:bg-blue-600">
              <Activity className="h-6 w-6 text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold">Health Analytics Report</h1>
              <p className="text-sm text-muted-foreground">
                {periodLabels[period]} Report • {getDateRange()}
              </p>
            </div>
          </div>
          <div className="text-right text-sm text-muted-foreground">
            <p>{text.generatedOn}: {new Date().toLocaleDateString()}</p>
            <p className="text-xs">{text.confidential}</p>
          </div>
        </div>
      </div>

      {/* Executive Summary */}
      <section>
        <h2 className="text-lg font-bold flex items-center gap-2 mb-4">
          <BarChart3 className="h-5 w-5" />
          {text.summary}
        </h2>
        <div className="grid grid-cols-4 gap-4">
          <div className="border rounded-lg p-4 text-center">
            <p className="text-3xl font-bold text-blue-600">{data.summary.totalConversations.toLocaleString()}</p>
            <p className="text-sm text-muted-foreground">{text.totalConversations}</p>
            <Badge variant={data.summary.conversationChange > 0 ? 'default' : 'destructive'} className="mt-1">
              {data.summary.conversationChange > 0 ? '↑' : '↓'} {Math.abs(data.summary.conversationChange)}%
            </Badge>
          </div>
          <div className="border rounded-lg p-4 text-center">
            <p className="text-3xl font-bold text-green-600">{data.summary.uniqueUsers.toLocaleString()}</p>
            <p className="text-sm text-muted-foreground">{text.uniqueUsers}</p>
            <Badge variant={data.summary.userChange > 0 ? 'default' : 'destructive'} className="mt-1">
              {data.summary.userChange > 0 ? '↑' : '↓'} {Math.abs(data.summary.userChange)}%
            </Badge>
          </div>
          <div className="border rounded-lg p-4 text-center">
            <p className="text-3xl font-bold text-red-600">{data.summary.emergenciesHandled}</p>
            <p className="text-sm text-muted-foreground">{text.emergenciesHandled}</p>
            <Badge variant={data.summary.emergencyChange < 0 ? 'default' : 'destructive'} className="mt-1">
              {data.summary.emergencyChange > 0 ? '↑' : '↓'} {Math.abs(data.summary.emergencyChange)}%
            </Badge>
          </div>
          <div className="border rounded-lg p-4 text-center">
            <p className="text-3xl font-bold text-purple-600">{data.summary.avgSatisfaction}/5</p>
            <p className="text-sm text-muted-foreground">{text.avgSatisfaction}</p>
            <Badge variant="secondary" className="mt-1">
              {data.summary.satisfactionChange > 0 ? '+' : ''}{data.summary.satisfactionChange} pts
            </Badge>
          </div>
        </div>
      </section>

      {/* Category Breakdown */}
      <section className="grid grid-cols-2 gap-8">
        <div>
          <h2 className="text-lg font-bold flex items-center gap-2 mb-4">
            <FileText className="h-5 w-5" />
            {text.categoryBreakdown}
          </h2>
          <div className="space-y-2">
            {data.categories.map((cat, i) => (
              <div key={i} className="flex items-center gap-2">
                <div className="w-32 text-sm truncate">{cat.name}</div>
                <div className="flex-1 h-4 bg-muted rounded-full overflow-hidden">
                  <div 
                    className="h-full bg-primary rounded-full" 
                    style={{ width: `${cat.percentage}%` }}
                  />
                </div>
                <div className="w-20 text-right text-sm text-muted-foreground">
                  {cat.count} ({cat.percentage}%)
                </div>
              </div>
            ))}
          </div>
        </div>

        <div>
          <h2 className="text-lg font-bold flex items-center gap-2 mb-4">
            <Languages className="h-5 w-5" />
            {text.languageUsage}
          </h2>
          <div className="space-y-2">
            {data.languages.map((lang, i) => {
              const colors = ['bg-blue-500', 'bg-orange-500', 'bg-green-500', 'bg-purple-500'];
              return (
                <div key={i} className="flex items-center gap-2">
                  <div className="w-20 text-sm">{lang.name}</div>
                  <div className="flex-1 h-4 bg-muted rounded-full overflow-hidden">
                    <div 
                      className={`h-full ${colors[i]} rounded-full`}
                      style={{ width: `${lang.percentage}%` }}
                    />
                  </div>
                  <div className="w-20 text-right text-sm text-muted-foreground">
                    {lang.count} ({lang.percentage}%)
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Risk Assessment */}
      <section>
        <h2 className="text-lg font-bold flex items-center gap-2 mb-4">
          <AlertTriangle className="h-5 w-5" />
          {text.riskAssessments}
        </h2>
        <div className="grid grid-cols-4 gap-4">
          {data.risks.map((risk, i) => {
            const colors = ['bg-green-100 text-green-800', 'bg-yellow-100 text-yellow-800', 'bg-orange-100 text-orange-800', 'bg-red-100 text-red-800'];
            return (
              <div key={i} className={`rounded-lg p-4 ${colors[i]}`}>
                <p className="font-bold text-2xl">{risk.count}</p>
                <p className="text-sm">{risk.level} Risk ({risk.percentage}%)</p>
              </div>
            );
          })}
        </div>
      </section>

      {/* Trends & Insights */}
      <section className="grid grid-cols-2 gap-8">
        <div>
          <h2 className="text-lg font-bold flex items-center gap-2 mb-4">
            <TrendingUp className="h-5 w-5" />
            {text.trends}
          </h2>
          <ul className="space-y-2">
            {data.trends.map((trend, i) => (
              <li key={i} className="flex items-start gap-2 text-sm">
                <span className="text-primary font-bold">•</span>
                <span>{trend}</span>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-bold flex items-center gap-2 mb-4">
            <Building2 className="h-5 w-5" />
            {text.recommendations}
          </h2>
          <ul className="space-y-2">
            {data.recommendations.map((rec, i) => (
              <li key={i} className="flex items-start gap-2 text-sm">
                <span className="text-green-600 font-bold">{i + 1}.</span>
                <span>{rec}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Footer */}
      <div className="border-t pt-4 mt-8 text-center text-sm text-muted-foreground print:fixed print:bottom-0 print:left-0 print:right-0 print:bg-white print:p-4">
        <p>{text.generatedBy}</p>
        <p className="text-xs mt-1">{text.confidential}</p>
      </div>
    </div>
  );
}

export function ReportGenerator({ onGenerate }: ReportGeneratorProps) {
  const { language } = useHealthPlatform();
  const text = REPORT_TEXT[language];
  const reportRef = useRef<HTMLDivElement>(null);

  const [period, setPeriod] = useState<ReportPeriod>('monthly');
  const [isGenerating, setIsGenerating] = useState(false);
  const [reportData, setReportData] = useState<typeof SAMPLE_REPORT_DATA | null>(null);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      if (onGenerate) {
        const data = await onGenerate(period);
        setReportData(data);
      } else {
        // Simulate generation
        await new Promise(resolve => setTimeout(resolve, 1500));
        setReportData(SAMPLE_REPORT_DATA);
      }
    } catch (error) {
      console.error('Failed to generate report:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    // Create a simple text/HTML download
    const element = document.getElementById('health-report');
    if (!element) return;

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Health Analytics Report</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; }
    h1, h2 { color: #1a365d; }
    .grid { display: grid; gap: 16px; }
    .grid-4 { grid-template-columns: repeat(4, 1fr); }
    .grid-2 { grid-template-columns: repeat(2, 1fr); }
    .card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; }
    .text-center { text-align: center; }
    .text-blue { color: #2563eb; }
    .text-green { color: #16a34a; }
    .text-red { color: #dc2626; }
    .text-purple { color: #7c3aed; }
    .text-sm { font-size: 14px; color: #64748b; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; }
    .badge-green { background: #dcfce7; color: #16a34a; }
    .badge-red { background: #fee2e2; color: #dc2626; }
  </style>
</head>
<body>
  ${element.innerHTML}
</body>
</html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `health-report-${period}-${new Date().toISOString().split('T')[0]}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Health Analytics Report',
          text: `Health report for ${period} period - Generated on ${new Date().toLocaleDateString()}`,
          url: window.location.href,
        });
      } catch (error) {
        console.log('Share cancelled');
      }
    } else {
      // Fallback: copy link
      navigator.clipboard.writeText(window.location.href);
      alert('Link copied to clipboard!');
    }
  };

  return (
    <div className="space-y-6">
      {/* Controls */}
      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5" />
                {text.title}
              </CardTitle>
              <CardDescription>{text.subtitle}</CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap items-center gap-4">
            {/* Period Selection */}
            <div className="flex items-center gap-2">
              <Calendar className="h-4 w-4 text-muted-foreground" />
              <span className="text-sm font-medium">{text.reportPeriod}:</span>
              <div className="flex gap-1">
                {(['weekly', 'monthly', 'quarterly'] as const).map((p) => (
                  <Button
                    key={p}
                    variant={period === p ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setPeriod(p)}
                  >
                    {text[p]}
                  </Button>
                ))}
              </div>
            </div>

            <Separator orientation="vertical" className="h-8" />

            {/* Actions */}
            <div className="flex gap-2">
              <Button onClick={handleGenerate} disabled={isGenerating}>
                {isGenerating ? (
                  <>
                    <span className="animate-spin mr-2">⏳</span>
                    Generating...
                  </>
                ) : (
                  <>
                    <BarChart3 className="h-4 w-4 mr-2" />
                    {text.generateReport}
                  </>
                )}
              </Button>
              
              {reportData && (
                <>
                  <Button variant="outline" onClick={handleDownload}>
                    <Download className="h-4 w-4 mr-2" />
                    {text.downloadPDF}
                  </Button>
                  <Button variant="outline" onClick={handlePrint}>
                    <Printer className="h-4 w-4 mr-2" />
                    {text.print}
                  </Button>
                  <Button variant="outline" onClick={handleShare}>
                    <Share2 className="h-4 w-4 mr-2" />
                    {text.share}
                  </Button>
                </>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Report Preview */}
      {reportData && (
        <Card className="print:shadow-none print:border-0">
          <CardContent className="p-0 overflow-hidden" ref={reportRef}>
            <ReportPreview 
              data={reportData} 
              period={period} 
              language={language}
              text={text}
            />
          </CardContent>
        </Card>
      )}

      {/* Print Styles */}
      <style jsx global>{`
        @media print {
          body * {
            visibility: hidden;
          }
          #health-report, #health-report * {
            visibility: visible;
          }
          #health-report {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
          .no-print {
            display: none !important;
          }
        }
      `}</style>
    </div>
  );
}
